/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ProjectTVF.ProjectTVF;
import controllers.*;
import entities.photo;
import java.util.List;
import jdk.nashorn.internal.codegen.CompilerConstants;
import oracle.jdbc.proxy.annotation.Pre;
/**
 *
 * @author PABLO_ARTURO
 */
public class Buscar_Foto extends javax.swing.JFrame {

    
    menu menuMain = null;
    
    public void setMenuMain(menu temp)
    {
        this.menuMain = temp;
    }
    /**
     * Creates new form Buscar_Foto
     */
    public Buscar_Foto() {
        initComponents();
    }
    
//    public void setLocationList()
//    {
//        
//    }
    
    public void setCountryList(List<String> Temp)
    {
        jComboBox_Country_List.addItem(null);
        for (String Temporal : Temp)
        {
            jComboBox_Country_List.addItem(Temporal);
        }
    }

    public void setEventList(List<String> Temp)
    {
        jComboBox_Event_List.addItem(null);
        for (String Temporal : Temp)
        {
            jComboBox_Event_List.addItem(Temporal);
        }
    }
    
    public void setCharacterList(List<String> Temp)
    {
        jComboBox_Character_List.addItem(null);
        for (String Temporal : Temp)
        {
            jComboBox_Character_List.addItem(Temporal);
        }
    }
    
    public void setTopicList(List<String> Temp)
    {
        jComboBox_Topic_List.addItem(null);
        for (String Temporal : Temp)
        {
            jComboBox_Topic_List.addItem(Temporal);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox_Country_List = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Event_List = new javax.swing.JComboBox<>();
        jComboBox_Character_List = new javax.swing.JComboBox<>();
        jComboBox_Topic_List = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Search_ALL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Search_C = new javax.swing.JButton();
        Search_E = new javax.swing.JButton();
        Search_CH = new javax.swing.JButton();
        Search_T = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox_Country_List.setSelectedItem(null);
        jComboBox_Country_List.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Country_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Country_ListActionPerformed(evt);
            }
        });

        jLabel1.setText("Country:");

        jComboBox_Event_List.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Event_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Event_ListActionPerformed(evt);
            }
        });

        jComboBox_Character_List.setSelectedItem(null);
        jComboBox_Character_List.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox_Topic_List.setSelectedItem(null);
        jComboBox_Topic_List.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Topic_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Topic_ListActionPerformed(evt);
            }
        });

        jLabel3.setText("Event:");

        jLabel4.setText("Character:");

        jLabel5.setText("Topic:");

        Search_ALL.setText("Search");
        Search_ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ALLActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search Photo");

        Search_C.setText("Search");
        Search_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_CActionPerformed(evt);
            }
        });

        Search_E.setText("Search");
        Search_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_EActionPerformed(evt);
            }
        });

        Search_CH.setText("Search");
        Search_CH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_CHActionPerformed(evt);
            }
        });

        Search_T.setText("Search");
        Search_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_TActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Search_ALL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_Country_List, 0, 147, Short.MAX_VALUE)
                    .addComponent(jComboBox_Event_List, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Topic_List, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Character_List, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_CH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Search_T, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Search_E, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Search_C, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Country_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Search_C))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Event_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Search_E))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Character_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Search_CH))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Topic_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Search_T))
                .addGap(18, 18, 18)
                .addComponent(Search_ALL)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ALLActionPerformed
        String Country = null;
        String Topic= null;
        String Character= null;
        String Event= null;

        
        boolean vacio = true;
        if(jComboBox_Character_List.getSelectedItem() != null )
        {
            Character = jComboBox_Character_List.getSelectedItem().toString();
            vacio = false;
        }
        
        if(jComboBox_Country_List.getSelectedItem() != null )
        {
            Country = jComboBox_Country_List.getSelectedItem().toString();
            vacio = false;
        }
        
        if(jComboBox_Event_List.getSelectedItem() != null )
        {
            Event = jComboBox_Event_List.getSelectedItem().toString();
            vacio = false;
        }
        
        if(jComboBox_Topic_List.getSelectedItem() != null )
        {
            Topic = jComboBox_Topic_List.getSelectedItem().toString();
            vacio = false;
        }
        
        
        
        
        //esto fue copiado y pegado, toca corregir
        if(vacio == true )
        {
            System.out.print("\n \n MIRAME K:_" + "NULL" + "_  \n \n" );
            // al ser seleccionado el valor null... se muestran todas las fotos de todos los paises
            menuMain.verTodasLasFotos();
        }
        else
        {        
            menuMain.verFotoXVariable(Country,Topic,Character,Event);         
        }
       
    }//GEN-LAST:event_Search_ALLActionPerformed

    private void jComboBox_Country_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Country_ListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Country_ListActionPerformed

    private void jComboBox_Event_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Event_ListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Event_ListActionPerformed

    private void jComboBox_Topic_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Topic_ListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Topic_ListActionPerformed

    private void Search_CHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_CHActionPerformed
        
        if(jComboBox_Character_List.getSelectedItem() == null)
        {
            System.out.print("\n \n MIRAME K:_" + "NULL" + "_  \n \n" );
            // al ser seleccionado el valor null... se muestran todas las fotos de todos los paises
            menuMain.verTodasLasFotos();
        }
        else
        {
            System.out.print("\n \n MIRAME K:_" + jComboBox_Character_List.getSelectedItem().toString() + "_  \n \n" );
            String TempText = jComboBox_Character_List.getSelectedItem().toString();
            menuMain.verFotoXCaracter(TempText);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_CHActionPerformed

    private void Search_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_TActionPerformed
        
        if(jComboBox_Topic_List.getSelectedItem() == null)
        {
            System.out.print("\n \n MIRAME K:_" + "NULL" + "_  \n \n" );
            // al ser seleccionado el valor null... se muestran todas las fotos de todos los paises
            menuMain.verTodasLasFotos();
        }
        else
        {
            System.out.print("\n \n MIRAME K:_" + jComboBox_Topic_List.getSelectedItem().toString() + "_  \n \n" );
            String TempText = jComboBox_Topic_List.getSelectedItem().toString();
            menuMain.verFotoXTopic(TempText);
        }
    }//GEN-LAST:event_Search_TActionPerformed

    private void Search_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_CActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox_Country_List.getSelectedItem() == null)
        {
            System.out.print("\n \n MIRAME K:_" + "NULL" + "_  \n \n" );
            // al ser seleccionado el valor null... se muestran todas las fotos de todos los paises
            menuMain.verTodasLasFotos();
        }
        else
        {
            System.out.print("\n \n MIRAME K:_" + jComboBox_Country_List.getSelectedItem().toString() + "_  \n \n" );
            String TempText = jComboBox_Country_List.getSelectedItem().toString();
            menuMain.verFotoXPais(TempText);
        }
        
        //ahora coneste dato del pais, ir al resultado de las fotos, compearar que pais tiene el que se tomo y llamar en la nueva pantalla la lista de paises resultantes
    }//GEN-LAST:event_Search_CActionPerformed

    private void Search_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_EActionPerformed
                if(jComboBox_Event_List.getSelectedItem() == null)
        {
            System.out.print("\n \n MIRAME K:_" + "NULL" + "_  \n \n" );
            // al ser seleccionado el valor null... se muestran todas las fotos de todos los paises
            menuMain.verTodasLasFotos();
        }
        else
        {
            System.out.print("\n \n MIRAME K:_" + jComboBox_Event_List.getSelectedItem().toString() + "_  \n \n" );
            String TempText = jComboBox_Event_List.getSelectedItem().toString();
            menuMain.verFotoXEvento(TempText);
        }
    }//GEN-LAST:event_Search_EActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar_Foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_Foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_Foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_Foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar_Foto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search_ALL;
    private javax.swing.JButton Search_C;
    private javax.swing.JButton Search_CH;
    private javax.swing.JButton Search_E;
    private javax.swing.JButton Search_T;
    private javax.swing.JComboBox<String> jComboBox_Character_List;
    private javax.swing.JComboBox<String> jComboBox_Country_List;
    private javax.swing.JComboBox<String> jComboBox_Event_List;
    private javax.swing.JComboBox<String> jComboBox_Topic_List;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
